{
 "title": "Experiment dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Spring boot - memory profile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"spring-boot-experiment\"})",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"spring-boot-experiment\"}",
     "legendFormat": "virtual memory"
    }
   ]
  },
  {
   "title": "Spring boot CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"spring-boot-experiment\"} / 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gin memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"gin-experiment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gin cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"gin-experiment\"}[30s]) / 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ktor - memory profile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"ktor-experiment\"})",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"ktor-experiment\"}",
     "legendFormat": "virtual memory"
    }
   ]
  },
  {
   "title": "Ktor - System cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"ktor-experiment\"} / 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dotnet - Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "system_runtime_gc_heap_size", "legendFormat": "GC Heap Size" },
    { "expr": "dotnet_total_memory_bytes", "legendFormat": "__auto" },
    {
     "expr": "system_runtime_dotnet_process_memory_working_set",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dotnet  - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"dotnet-experiment\"} / 2",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Flask memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"flask-experiment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flask cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"flask-experiment\"}[30s]) / 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Express memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"express-experiment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Express cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"express-experiment\"}[30s]) / 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application ready time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_max",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Appenders",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(process_cpu_usage{job=\"spring-boot-experiment\"})",
       "legendFormat": "active_appenders"
      },
      {
       "expr": "sum(process_open_fds{job=\"prometheus\"})",
       "legendFormat": "open_fds"
      }
     ]
    },
    {
     "title": "System cpu usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 7, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "system_cpu_usage", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "WAL Corruptions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "up{job=\"spring-boot-experiment\"}"
      }
     ]
    },
    {
     "title": "Scrape Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, max(scrape_duration_seconds) by (job))",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  }
 ]
}